apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: pulse
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: aviadbi1/myrepo:0.0.4
          env:
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
