## CREATE Jaeger-Operator and Jaeger instance
# helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
# kubectl create namespace pulse
# helm install jaeger-operator jaegertracing/jaeger-operator --version 2.12.3 --set rbac.clusterRole=true --namespace=pulse
# kubectl apply -f jaeger.yaml
# kubectl get jaegers
# kubectl get ingress

## Create this image
# docker login
# docker build -t aviadbi1/myrepo:0.0.2 .
# docker push aviadbi1/myrepo:0.0.2
# docker run -d -p 3000:3000 aviadbi1/myrepo:0.0.2
# kubectl create deployment trace-try --image=aviadbi1/myrepo:0.0.2 --namespace=pulse

## DELETE Jaeger
# kubectl delete jaeger simple
# kubectl delete crd jaegers.jaegertracing.io
# helm delete jaeger-operator

# kubectl expose deployment jaeger-operator --type=NodePort --name=example-service
# kubectl cluster-info

apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple
  namespace: pulse
spec:
  ingress:
    enabled: true
  strategy: allInOne
  sampling:
    options:
      default_strategy:
        type: const
        param: 1
